#!/usr/bin/env python

Import("env")
Import("env_modules")

env_lua = env_modules.Clone()

# Godot source files

module_obj = []

env_lua.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
